### ISSUE TITLE
Upgrade Solidity version

### ISSUE THREAD

**Issue by jpc20** [Eth-Crowdfund/eth-crowdfund-fe#11]
We are currently using an old version of Solidity and the solc compiler. Updating the compiler will cause the contracts to fail because the new solc compiler doesn't support the Solidity version we are using.

**Comment by edmdc** [comment]
If I uninstall the current solc compiler, and re-install/lock the version to the one stated on top of the solidity file, could this solve the issue??

**Comment by jpc20** [comment]
@emontealvo I think we'll need to run with solc version `^0.4.25` for now because that is the one that works with our current Solidity version, but we can plan to upgrade those as we move forward.
